package dev.agentshell.app.ui.apps

import android.content.Context
import android.content.pm.PackageManager
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.material3.Text
import dev.agentshell.app.ui.theme.AgentShellColors
import dev.agentshell.app.ui.theme.AgentShellTypography
import dev.agentshell.app.ui.components.ShellPanel
import dev.agentshell.app.miniapp.MiniAppEntity

@Composable
fun AppsHubScreen(
    miniApps: List<MiniAppEntity>,
    onOpenMiniApp: (String) -> Unit,
    onOpenMiniAppsList: () -> Unit
) {
    val context = LocalContext.current

    // Only show installed apps as requested
    val controlledApps = remember { buildControlledAppList(context).filter { it.isInstalled } }

    LazyColumn(
        modifier = Modifier
            .fillMaxSize()
            .background(AgentShellColors.TermBg)
            .padding(horizontal = 16.dp, vertical = 12.dp),
        verticalArrangement = Arrangement.spacedBy(16.dp)
    ) {
        // ── Section 1: Mini Apps ───────────────────────────────────────────────
        item {
            ShellPanel(header = "MINI APPS // GENERATED BY AGENT") {
                Column(modifier = Modifier.padding(8.dp)) {
                    if (miniApps.isEmpty()) {
                        Text(
                            text = "No apps yet — ask the agent to build one",
                            color = AgentShellColors.Text3,
                            style = AgentShellTypography.bodySmall,
                            modifier = Modifier.padding(start = 8.dp, bottom = 8.dp)
                        )
                    } else {
                        miniApps.chunked(2).forEach { rowApps ->
                            Row(modifier = Modifier.fillMaxWidth()) {
                                rowApps.forEach { app ->
                                    MiniAppChip(
                                        app = app,
                                        modifier = Modifier
                                            .weight(1f)
                                            .padding(4.dp)
                                            .clickable { onOpenMiniApp(app.id) }
                                    )
                                }
                                if (rowApps.size == 1) Spacer(modifier = Modifier.weight(1f))
                            }
                        }
                    }
                }
            }
        }

        // ── Section 2: Installed Apps ────────────────────────────────────────
        item {
            ShellPanel(header = "INSTALLED APPS // AGENT CAN CONTROL") {
                Column(modifier = Modifier.padding(8.dp)) {
                    if (controlledApps.isEmpty()) {
                        Text(
                            text = "No supported apps installed.",
                            color = AgentShellColors.Text3,
                            style = AgentShellTypography.bodySmall,
                            modifier = Modifier.padding(start = 8.dp, bottom = 8.dp)
                        )
                    } else {
                        Text(
                            text = "Tap any app to let the agent control it",
                            color = AgentShellColors.Text3,
                            style = AgentShellTypography.bodySmall,
                            modifier = Modifier.padding(start = 8.dp, bottom = 8.dp)
                        )
                        controlledApps.chunked(2).forEach { rowApps ->
                            Row(modifier = Modifier.fillMaxWidth()) {
                                rowApps.forEach { app ->
                                    AppChip(
                                        app = app,
                                        modifier = Modifier
                                            .weight(1f)
                                            .padding(4.dp)
                                    )
                                }
                                if (rowApps.size == 1) Spacer(modifier = Modifier.weight(1f))
                            }
                        }
                    }
                }
            }
        }
    }
}

@Composable
private fun MiniAppChip(
    app: MiniAppEntity,
    modifier: Modifier = Modifier
) {
    Column(
        modifier = modifier
            .border(1.dp, AgentShellColors.Amber)
            .background(AgentShellColors.Shell1)
            .padding(12.dp)
    ) {
        Text(
            text = app.name,
            color = AgentShellColors.Amber,
            style = AgentShellTypography.bodySmall,
            fontWeight = FontWeight.Bold
        )
        Spacer(modifier = Modifier.height(4.dp))
        Text(
            text = app.description,
            color = AgentShellColors.Text3,
            style = AgentShellTypography.labelSmall,
            maxLines = 2
        )
    }
}

@Composable
private fun AppChip(
    app: ControlledApp,
    modifier: Modifier = Modifier
) {
    val statusColor = if (app.isInstalled) AgentShellColors.Success else AgentShellColors.Text4

    Column(
        modifier = modifier
            .border(1.dp, if (app.isInstalled) AgentShellColors.Shell3 else AgentShellColors.Shell2)
            .background(AgentShellColors.Shell1)
            .padding(12.dp)
    ) {
        Row(verticalAlignment = Alignment.CenterVertically) {
            Box(
                modifier = Modifier
                    .size(7.dp)
                    .background(statusColor)
            )
            Spacer(modifier = Modifier.width(8.dp))
            Text(
                text = app.name,
                color = if (app.isInstalled) AgentShellColors.Text0 else AgentShellColors.Text4,
                style = AgentShellTypography.bodySmall,
                fontWeight = if (app.isInstalled) FontWeight.Bold else FontWeight.Normal
            )
        }
        Spacer(modifier = Modifier.height(8.dp))
        Text(
            text = "Access: ${app.capabilities.joinToString(", ")}",
            color = AgentShellColors.Text3,
            style = AgentShellTypography.labelSmall
        )
        Spacer(modifier = Modifier.height(4.dp))
        Text(
            text = "Tools: ${app.toolCalls.joinToString(", ")}",
            color = AgentShellColors.Text2,
            style = AgentShellTypography.labelSmall
        )
    }
}

// ── Data ─────────────────────────────────────────────────────────────────────

data class ControlledApp(
    val name: String,
    val packageName: String,
    val isInstalled: Boolean,
    val capabilities: List<String>,
    val toolCalls: List<String>
)

private fun buildControlledAppList(context: Context): List<ControlledApp> {
    val pm = context.packageManager
    val apps = listOf(
        ControlledApp("WhatsApp", "com.whatsapp", false, listOf("Contacts", "Storage"), listOf("send_message", "read_chat")),
        ControlledApp("Spotify", "com.spotify.music", false, listOf("Media"), listOf("play_music", "search_song")),
        ControlledApp("YouTube", "com.google.android.youtube", false, listOf("Media", "Network"), listOf("search_video", "play_video")),
        ControlledApp("Gmail", "com.google.android.gm", false, listOf("Accounts", "Storage"), listOf("send_email", "read_email")),
        ControlledApp("Chrome", "com.android.chrome", false, listOf("Network", "Storage"), listOf("open_url", "search_web")),
        ControlledApp("Photos", "com.google.android.apps.photos", false, listOf("Storage"), listOf("view_photo")),
        ControlledApp("Ola", "com.olacabs.customer", false, listOf("Location"), listOf("book_ride")),
        ControlledApp("Uber", "com.ubercabs.rider", false, listOf("Location"), listOf("book_ride")),
        ControlledApp("Swiggy", "in.swiggy.android", false, listOf("Location"), listOf("order_food")),
        ControlledApp("Zomato", "com.application.zomato", false, listOf("Location"), listOf("order_food")),
        ControlledApp("Instagram", "com.instagram.android", false, listOf("Camera", "Storage"), listOf("post_photo", "read_feed")),
        ControlledApp("Twitter/X", "com.twitter.android", false, listOf("Network"), listOf("post_tweet", "read_timeline")),
        ControlledApp("Maps", "com.google.android.apps.maps", false, listOf("Location"), listOf("navigate", "search_place")),
        ControlledApp("Play Store", "com.android.vending", false, listOf("Network"), listOf("install_app")),
        ControlledApp("Splitwise", "com.Splitwise.SplitwiseMobile", false, listOf("Contacts"), listOf("add_expense")),
        ControlledApp("Notion", "notion.id", false, listOf("Network"), listOf("read_page", "write_page"))
    )
    return apps.map { app ->
        app.copy(
            isInstalled = try {
                pm.getPackageInfo(app.packageName, 0)
                true
            } catch (e: PackageManager.NameNotFoundException) {
                false
            }
        )
    }
}
