package dev.agentshell.app.miniapp

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import dagger.hilt.android.lifecycle.HiltViewModel
import dev.agentshell.app.agent.AgentLoopManager
import dev.agentshell.app.agent.AgentState
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.launch
import javax.inject.Inject

@HiltViewModel
class MiniAppsViewModel @Inject constructor(
    private val dao: MiniAppDao,
    agentLoopManager: AgentLoopManager
) : ViewModel() {

    val miniApps: StateFlow<List<MiniAppEntity>> = dao.getAll()
        .stateIn(viewModelScope, SharingStarted.WhileSubscribed(5_000), emptyList())

    /** Exposes the name of the app currently being generated by the LLM. */
    val buildingAppName: StateFlow<String?> = agentLoopManager.agentState
        .map { state ->
            if (state is AgentState.Acting && state.tool == "create_mini_app") {
                state.params["name"] ?: state.params["title"] ?: "Unnamed App"
            } else {
                null
            }
        }
        .stateIn(viewModelScope, SharingStarted.WhileSubscribed(5_000), null)

    /** Load a single mini-app by ID. Used by [MiniAppDetailScreen]. */
    suspend fun getById(id: String): MiniAppEntity? = dao.getById(id)

    fun deleteMiniApp(id: String) {
        viewModelScope.launch {
            dao.deleteById(id)
        }
    }
}
